# CON LOS DATOS DE CANCIONES, ELIJA LAS 3 COLUMNAS QUE USTED DESEE Y ORDENELAS ASCENDENTEMENTE

In [ ]:
import pandas as pd

data = pd.read_csv('musica.csv')

## Ordernar musica por artistas

In [ ]:
data.sort_values('artists', ascending = True)

,id,name,artists,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms,time_signature
23,2iUXsYOEPhVqEBwsqP70r,Youngblood,5 Seconds of Summer,0.596,0.854,7,-5.114,0,0.4630,0.0169,0.000000,0.124,0.1520,120.274,203418,4
55,2E124GmJRnBJuXbTb4cPU,FEFE (feat. Nicki Minaj & Murda Beatz),6ix9ine,0.931,0.387,1,-9.127,1,0.4120,0.0880,0.000000,0.136,0.3760,125.978,179405,4
88,3Ga6eKrUFf12ouh9Yw3v2,Downtown,Anitta,0.775,0.679,4,-4.985,0,0.1350,0.1800,0.000073,0.068,0.6190,166.008,193456,4
60,2BgEsaKNfHUdlh97KmvFy,2002,Anne-Marie,0.697,0.683,1,-2.881,0,0.1170,0.0372,0.000000,0.137,0.6030,96.133,186987,4
65,5OCJzvD7sykQEKHH7qAC3,God is a woman,Ariana Grande,0.602,0.658,1,-5.934,1,0.0558,0.0233,0.000060,0.237,0.2680,145.031,197547,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1,3ee8Jmje8o58CHK66QrVC,SAD!,XXXTENTACION,0.740,0.613,8,-4.880,1,0.1450,0.2580,0.003720,0.123,0.4730,75.023,166606,4
98,1j4kHkkpqZRBwE0A4CN4Y,Dusk Till Dawn - Radio Edit,ZAYN,0.258,0.437,11,-6.593,0,0.0390,0.1010,0.000001,0.106,0.0967,180.043,239000,4
95,630sXRhIcfwr2e4RdNtjK,Rewrite The Stars,Zac Efron,0.684,0.619,10,-7.005,1,0.0386,0.0716,0.000000,0.122,0.2840,125.046,217440,4
14,09IStsImFySgyp0pIQdqA,The Middle,Zedd,0.753,0.657,7,-3.061,1,0.0449,0.1710,0.000000,0.112,0.4370,107.010,184732,4
35,0d2iYfpKoM0QCKvcLCkBa,Eastside (with Halsey & Khalid),benny blanco,0.560,0.680,6,-7.648,0,0.3210,0.5550,0.000000,0.116,0.3190,89.391,173800,4

## Ordernar musica por nombre

In [ ]:
data.sort_values('name', ascending = True)

,id,name,artists,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms,time_signature
77,4QtiVmuA88tPQiCOHZuQ5,"1, 2, 3 (feat. Jason Derulo & De La Ghetto)",Sofia Reyes,0.792,0.895,1,-3.112,0,0.0589,0.1650,0.000000,0.0501,0.794,94.968,201526,4
60,2BgEsaKNfHUdlh97KmvFy,2002,Anne-Marie,0.697,0.683,1,-2.881,0,0.1170,0.0372,0.000000,0.1370,0.603,96.133,186987,4
34,2hl6q70unbviGo3g1R7uF,?chame La Culpa,Luis Fonsi,0.726,0.889,0,-3.655,1,0.0429,0.0328,0.000000,0.0925,0.649,96.024,173720,4
15,3GCdLUSnKSMJhs4Tj6CV3,All The Stars (with SZA),Kendrick Lamar,0.698,0.633,8,-4.946,1,0.0597,0.0605,0.000194,0.0926,0.552,96.924,232187,4
47,4hQ6UGyWQIGJmHSo0J88J,Back To You - From 13 Reasons Why ? Season 2 S...,Selena Gomez,0.601,0.724,6,-4.856,1,0.0486,0.0945,0.000002,0.1200,0.508,102.061,207905,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23,2iUXsYOEPhVqEBwsqP70r,Youngblood,5 Seconds of Summer,0.596,0.854,7,-5.114,0,0.4630,0.0169,0.000000,0.1240,0.152,120.274,203418,4
38,7AFASza1mXqntmGtbxXpr,changes,XXXTENTACION,0.669,0.308,11,-10.068,1,0.0290,0.8830,0.000000,0.0984,0.520,64.934,121887,4
80,0u2P5u6lvoDfwTYjAADbn,lovely (with Khalid),Billie Eilish,0.351,0.296,4,-10.109,0,0.0333,0.9340,0.000000,0.0950,0.120,115.284,200186,4
16,2qT1uLXPVPzGgFOx4jtEu,no tears left to cry,Ariana Grande,0.699,0.713,9,-5.507,0,0.0594,0.0400,0.000003,0.2940,0.354,121.993,205920,4
2,0e7ipj03S05BNilyu5bRz,rockstar (feat. 21 Savage),Post Malone,0.587,0.535,5,-6.090,0,0.0898,0.1170,0.000066,0.1310,0.140,159.847,218147,4

## Ordernar musica por energia

In [ ]:
data.sort_values('energy', ascending = True)

,id,name,artists,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms,time_signature
80,0u2P5u6lvoDfwTYjAADbn,lovely (with Khalid),Billie Eilish,0.351,0.296,4,-10.109,0,0.0333,0.9340,0.000000,0.0950,0.120,115.284,200186,4
84,1bhUWB0zJMIKr9yVPrkEu,Perfect Duet (Ed Sheeran & Beyonc?),Ed Sheeran,0.587,0.299,8,-7.365,1,0.0263,0.7790,0.000000,0.1230,0.356,94.992,259550,3
38,7AFASza1mXqntmGtbxXpr,changes,XXXTENTACION,0.669,0.308,11,-10.068,1,0.0290,0.8830,0.000000,0.0984,0.520,64.934,121887,4
91,6vN77lE9LK6HP2DewaN6H,Yes Indeed,Lil Baby,0.964,0.346,5,-9.309,0,0.5300,0.0350,0.000000,0.1080,0.562,119.958,142273,4
52,1mXVgsBdtIVeCLJnSnmtd,Too Good At Goodbyes,Sam Smith,0.698,0.375,5,-8.279,1,0.0491,0.6520,0.000000,0.1730,0.534,91.920,201000,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7,7ef4DlsgrMEH11cDZd32M,One Kiss (with Dua Lipa),Calvin Harris,0.791,0.862,9,-3.240,0,0.1100,0.0370,0.000022,0.0814,0.592,123.994,214847,4
9,08bNPGLD8AhKpnnERrAc6,FRIENDS,Marshmello,0.626,0.880,9,-2.384,0,0.0504,0.2050,0.000000,0.1280,0.534,95.079,202621,4
34,2hl6q70unbviGo3g1R7uF,?chame La Culpa,Luis Fonsi,0.726,0.889,0,-3.655,1,0.0429,0.0328,0.000000,0.0925,0.649,96.024,173720,4
77,4QtiVmuA88tPQiCOHZuQ5,"1, 2, 3 (feat. Jason Derulo & De La Ghetto)",Sofia Reyes,0.792,0.895,1,-3.112,0,0.0589,0.1650,0.000000,0.0501,0.794,94.968,201526,4
12,3CA9pLiwRIGtUBiMjbZmR,Nice For What,Drake,0.586,0.909,8,-6.474,1,0.0705,0.0891,0.000109,0.1190,0.757,93.394,210747,4